##eureka server服务端口
#
spring:
  application:
    name: lagou-cloud-eureka-server #应用名称，应用名称会在Eureka中作为服务名称

---
#第一个profile,后期启动spring-boot项目时，可通过命令参数指定
spring:
  profiles: LagouCloudEurekaServerA
server:
  port: 8761
    #eureka 客户端配置（和Serve交互）,Eureka Server其实也是一个Client

eureka:
  instance:
    hostname: LagouCloudEurekaServerA #当前eureka主机实例的主机名
  client:
    service-url: #配置客户端交互的Eureka Server地址
      defaultZone: http://LagouCloudEurekaServerB:8762/eureka  #固定写法：http://localhost:8761/eureka
    register-with-eureka: true #当前自己就是Server,不需要注册自己;集群模式下为true
    fetch-registry: true #查询获取注册中心的服务信息，自己就是server,不需要从Eureka Server获取服务信息，默认是true,设置为false;集群模式下为true
---
spring:
  profiles: LagouCloudEurekaServerB
server:
  port: 8762
eureka:
  instance:
    hostname: LagouCloudEurekaServerB
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka



